# Generated by Django 5.1.3 on 2024-11-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Example',
            new_name='Hotel',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Username',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='query',
            new_name='date',
        ),
    ]
