# Generated by Django 5.1.3 on 2024-11-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_example_contact_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='messsage',
            field=models.CharField(default='datetime', max_length=122),
        ),
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default='datetime', max_length=122),
        ),
    ]
