# Generated by Django 5.1.3 on 2024-12-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_register_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='num',
            field=models.TextField(default='datetime'),
        ),
    ]
