# Generated by Django 5.1.3 on 2025-01-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_register_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='num',
            field=models.IntegerField(),
        ),
    ]
