# Generated by Django 5.1.3 on 2025-01-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_register_budget_alter_register_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('messagess', models.CharField(max_length=222)),
                ('myphone', models.IntegerField()),
            ],
        ),
    ]
