# Generated by Django 5.1.3 on 2025-01-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_myphone_contactus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='country',
            field=models.CharField(default='No country', max_length=122),
        ),
        migrations.AlterField(
            model_name='register',
            name='messsage',
            field=models.CharField(default='No message', max_length=122),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(default='No username', max_length=122),
        ),
    ]
